#############################################################################
# Generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#  Apr 22, 2020 12:07:54 AM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #ff00ff
set vTcl(analog_color_p) #00ff80
set vTcl(analog_color_m) #80ff00
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) #0000ff
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top58 {base} {
    global vTcl
    if {$base == ""} {
        set base .top58
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 966x728+485+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra61 \
        -borderwidth 2 -relief groove -background #000 -height 725 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 965 
    vTcl:DefineAlias "$top.fra61" "mainFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra61
    frame $site_3_0.fra62 \
        -relief groove -background #000 -height 83 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 651 
    vTcl:DefineAlias "$site_3_0.fra62" "titleFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra62
    label $site_4_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #000 \
        -disabledforeground #a3a3a3 -font {-family {Tw Cen MT} -size 23} \
        -foreground #fff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Méthode De dichotomie} 
    vTcl:DefineAlias "$site_4_0.lab63" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab63 \
        -in $site_4_0 -x 0 -relx 0.031 -y 0 -rely 0.12 -width 0 \
        -relwidth 0.917 -height 0 -relheight 0.627 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra64 \
        -relief groove -background #000 -height 504 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 794 
    vTcl:DefineAlias "$site_3_0.fra64" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra64
    entry $site_4_0.ent66 \
        -background #000 -disabledbackground #9bd2aa \
        -disabledforeground #a3a3a3 -font {-family {Tw Cen MT} -size 20} \
        -foreground #00ff00 -highlightbackground #00ff00 \
        -highlightcolor #00ff00 -highlightthickness 1 \
        -insertbackground #00ff00 -insertborderwidth 1 -relief flat \
        -selectbackground #c4c4c4 -selectforeground black -width 724 
    vTcl:DefineAlias "$site_4_0.ent66" "entryFomule" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000 -cursor arrow -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 20} -foreground #fff \
        -highlightbackground #00ff00 -highlightcolor #00ff00 \
        -highlightthickness 2 -pady 0 -relief ridge -text Solve 
    vTcl:DefineAlias "$site_4_0.but69" "btnSolve" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black -background #000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 24 -weight bold} \
        -foreground #fff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text f(x) 
    vTcl:DefineAlias "$site_4_0.lab73" "Label2_10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent44 \
        -background #000 -disabledbackground #9bd2aa \
        -disabledforeground #a3a3a3 -font {-family {Tw Cen MT} -size 20} \
        -foreground #00ff00 -highlightbackground #00ff00 \
        -highlightcolor #00ff00 -highlightthickness 1 \
        -insertbackground #00ff00 -insertborderwidth 1 -relief flat \
        -selectbackground #c4c4c4 -selectforeground black -width 334 
    vTcl:DefineAlias "$site_4_0.ent44" "entryA" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 24 -weight bold} \
        -foreground #fff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text a 
    vTcl:DefineAlias "$site_4_0.lab45" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #000 \
        -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 24 -weight bold} \
        -foreground #fff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text b 
    vTcl:DefineAlias "$site_4_0.lab46" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent48 \
        -background #000 -disabledbackground #9bd2aa \
        -disabledforeground #a3a3a3 -font {-family {Tw Cen MT} -size 20} \
        -foreground #00ff00 -highlightbackground #00ff00 \
        -highlightcolor #00ff00 -highlightthickness 1 \
        -insertbackground #00ff00 -insertborderwidth 1 -relief flat \
        -selectbackground #c4c4c4 -selectforeground black -width 334 
    vTcl:DefineAlias "$site_4_0.ent48" "entryB" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent66 \
        -in $site_4_0 -x 0 -relx 0.05 -y 0 -rely 0.179 -width 724 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but69 \
        -in $site_4_0 -x 0 -relx 0.315 -y 0 -rely 0.732 -width 276 \
        -relwidth 0 -height 53 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab73 \
        -in $site_4_0 -x 0 -relx 0.415 -y 0 -rely 0.02 -width 0 \
        -relwidth 0.126 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent44 \
        -in $site_4_0 -x 0 -relx 0.05 -y 0 -rely 0.417 -width 334 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 0 -relx 0.189 -y 0 -rely 0.298 -width 0 \
        -relwidth 0.113 -height 0 -relheight 0.093 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 0 -relx 0.679 -y 0 -rely 0.298 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.093 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent48 \
        -in $site_4_0 -x 0 -relx 0.541 -y 0 -rely 0.417 -width 334 \
        -relwidth 0 -height 54 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #b0b8ce -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 20} -foreground #000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text {Go Back} 
    vTcl:DefineAlias "$site_3_0.but70" "btnRetour" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra62 \
        -in $site_3_0 -x 0 -relx 0.166 -y 0 -rely 0.041 -width 0 \
        -relwidth 0.674 -height 0 -relheight 0.114 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra64 \
        -in $site_3_0 -x 0 -relx 0.104 -y 0 -rely 0.151 -width 0 \
        -relwidth 0.823 -height 0 -relheight 0.692 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 0 -relx 0.031 -y 0 -rely 0.893 -width 186 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra61 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top58 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

